### ISSUE TITLE
livetables are being displayed wrongly

### ISSUE THREAD

**Issue by cjdelisle** [RISCOSS/riscoss-wiki-ui#18]
to reproduce:
* goto the riscoss main page with enough projects to cause the livetable to be paginated
* click page 2
* click page 1
* observe the pagination is screwed up

**Comment by lidix91** [comment]
If you select more results per page (e.g.100), the list is not correct. There are duplicated entries

**Comment by slauriere** [comment]
As far as I know this issue is fixed in version 2 which will be deployed soon. Let me add it to the corresponding milestone for the record.

**Comment by lidix91** [comment]
in the public version I can access (http://riscossplatform.ow2.org/riscoss/wiki/githubanalyser/view/Main/) is still happening. I don't know if is fixed in version 2, the version I can see has version 0.24 in the main page

**Comment by cjdelisle** [comment]
fixed in v2
